version: '3'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    command: ["./utils/wait-for-it/wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
      - .:/go/src/github.com/swinslow/containerapp
    ports:
      - "3005:3005"
    depends_on:
      - db
    environment:
      WEBPORT: 3005

  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
    ports:
      - 5432:5432

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - './webapp:/webapp'
      - '/webapp/node_modules'
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
