version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432

  app:
    build: .
    command: ["./utils/wait-for-it/wait-for-it.sh", "db:5432", "--", "go", "run", "webapp/main.go"]
    volumes:
      - .:/go/src/github.com/swinslow/containerapp
    ports:
      - "8080:3005"
    depends_on:
      - db
    environment:
      WEBPORT: 3005
